# Generated by Django 5.0 on 2024-01-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_category_delete_shirt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
